sentences = [
    ['Great job on the project! Keep up the good work!', 0],
    ['I hope everyone has a wonderful weekend.', 0],
    ['Your opinion is valid, even if I don’t fully agree with it.', 0],
    ['Thanks for sharing this information. It was really helpful!', 0],
    ['Let’s all work together to solve this issue peacefully.', 0],
    ['I enjoyed reading your post. It gave me a lot to think about.', 0],
    ['I believe that respectful dialogue is key to understanding each other.', 0],
    ['Nice picture! The scenery is absolutely beautiful.', 0],
    ['Looking forward to your next post. Keep inspiring!', 0],
    ['I really appreciate your effort on this task. Well done!', 0],
    ['It’s always a pleasure to hear your thoughts.', 0],
    ['You did an excellent job handling that situation.', 0],
    ['Your input was crucial in moving this project forward. Thank you!', 0],
    ['The way you approached the problem was really impressive.', 0],
    ['Your feedback really helped me see things from a new perspective.', 0],
    ['I admire how you stay calm and composed under pressure.', 0],
    ['You’re doing amazing work—keep it up!', 0],
    ['Thank you for your detailed explanation. It was very enlightening.', 0],
    ['You have such a creative approach to problem-solving.', 0],
    ['Thanks for being such a great team player.', 0],
    ['I love how you handle feedback with such grace.', 0],
    ['Your dedication to the project really shows.', 0],
    ['I appreciate your positivity. It’s contagious!', 0],
    ['It’s amazing how much you’ve accomplished in such a short time.', 0],
    ['Your teamwork is something to be proud of.', 0],
    ['I’m impressed with how you keep things organized and on track.', 0],
    ['Your contributions are always so thoughtful and meaningful.', 0],
    ['That was a fantastic presentation. You really engaged the audience!', 0],
    ['I appreciate how you always go the extra mile.', 0],
    ['Your attention to detail is really impressive.', 0],
    ['You always bring a fresh perspective to the table.', 0],
    ['Thanks for your hard work. It doesn’t go unnoticed!', 0],
    ['You’ve got a great way of making complex ideas easy to understand.', 0],
    ['I’m grateful for your help with this task!', 0],
    ['You’re doing a fantastic job, and I can’t wait to see more!', 0],
    ['I really respect your dedication to continuous learning.', 0],
    ['You handled that challenge really well—great job!', 0],
    ['I’m so glad you’re part of this team!', 0],
    ['You always know how to make the best out of any situation.', 0],
    ['I appreciate your kindness and willingness to help others.', 0],
    ['Your ability to stay organized is something I truly admire.', 0],
    ['You always bring positivity to every meeting!', 0],
    ['I love how you encourage collaboration among the team.', 0],
    ['You’re doing an incredible job at balancing everything.', 0],
    ['It’s clear that you put a lot of thought and effort into your work.', 0],
    ['I can always count on you to follow through on your commitments.', 0],
    ['I appreciate how you approach challenges with a solution-oriented mindset.', 0],
    ['Your leadership is truly inspiring.', 0],
    ['You did a great job managing the team through this project!', 0],
    ['Your work ethic is something I really respect.', 0],
    ['You’ve made great progress on this project. Well done!', 0],
    ['I appreciate how you remain open-minded and receptive to new ideas.', 0],
    ['Your positivity is a great asset to the team.', 0],
    ['I’m always learning something new from you.', 0],
    ['I’m impressed by your ability to stay focused and get things done.', 0],
    ['You bring such a great energy to the group!', 0],
    ['You’ve been doing such an excellent job lately. Keep it up!', 0],
    ['It’s always so refreshing to work with you.', 0],
    ['I love how you approach problems with such creativity.', 0],
    ['You did an outstanding job with that presentation!', 0],
    ['I’m so grateful for the support you’ve provided throughout this project.', 0],
    ['You really have a knack for finding solutions that work for everyone.', 0],
    ['Your organizational skills are second to none.', 0],
    ['You’ve handled the situation with such grace and professionalism.', 0],
    ['You are making such a positive impact in everything you do!', 0],
    ['I’m so impressed with how you manage your time and tasks.', 0],
    ['You always take the time to think things through thoroughly.', 0],
    ['You’re such a valuable part of this team.', 0],
    ['You really made a difference in that meeting—well done!', 0],
    ['You’ve handled that challenge like a pro!', 0],
    ['Your positive attitude makes all the difference in this team.', 0],
    ['I admire your ability to stay calm and focused under pressure.', 0],
    ['Your enthusiasm and energy are always appreciated!', 0],
    ['You’ve done an excellent job keeping everything on track.', 0],
    ['I appreciate your openness to feedback and improvement.', 0],
    ['You’re doing an amazing job, and I look forward to seeing your progress.', 0],
    ['Your ability to collaborate and connect with others is truly special.', 0],
    ['Thanks for always being there to lend a helping hand.', 0],
    ['Your problem-solving skills are truly impressive.', 0],
    ['I really appreciate the insights you bring to the table.', 0],
    ['You’re handling this project with such professionalism. Keep it up!', 0],
    ['You’ve been a huge help in making this project a success.', 0],
    ['I’m really impressed with your ability to adapt and learn quickly.', 0],
    ['You’ve been doing such an incredible job—keep up the great work!', 0],
    ['I love how you’re always willing to step up when needed.', 0],
    ['You’ve done a fantastic job coordinating all the moving parts of this project.', 0],
    ['I admire how you approach tasks with such enthusiasm.', 0],
    ['Your attention to detail has really made a difference.', 0],
    ['You’re an invaluable member of this team!', 0],
    ['I love how you’re always thinking ahead and planning for the future.', 0],
    ['Your commitment to quality is something I truly appreciate.', 0],
    ['You did an excellent job managing this project from start to finish.', 0],
    ['I really value your insights and opinions—they’re always so thoughtful.', 0],
    ['You’re doing an amazing job at keeping everything on track!', 0],
    ['Your hard work and dedication have made a real impact.', 0],
    ['I appreciate how you make sure to communicate clearly with everyone.', 0],
    ['You’ve done an amazing job bringing this project to life!', 0],
    ['I’m so glad to be working with someone as dedicated as you.', 0],
    ["If you show your face here again, you’re going to regret it.", 1],
    ["Someone should teach you a lesson you’ll never forget.", 1],
    ["I’ll make sure you pay for what you did. Watch your back.", 1],
    ["Don’t push me, or you’ll see what I’m capable of.", 1],
    ["People like you deserve to be hurt for saying things like that.", 1],
    ["You better be careful, or something bad might happen to you.", 1],
    ["I’m going to find you and make you pay for this.", 1],
    ["Everyone would be better off if you just disappeared.", 1],
    ["You’ll wish you never crossed me after what I do to you.", 1],
    ["One day, you’re going to get exactly what’s coming to you.", 1],
    ["Don’t think I’ve forgotten what you did. I’ll make you regret it.", 1],
    ["You can’t hide from me forever. I’ll make sure you suffer.", 1],
    ["Keep testing me, and you’ll see how far I’m willing to go.", 1],
    ["You think you’re safe, but I’m always watching.", 1],
    ["You’re making a huge mistake by underestimating me.", 1],
    ["You’ll pay for every word you’ve ever said.", 1],
    ["Watch your step, or I’ll make sure you regret it.", 1],
    ["You better pray I don’t get my hands on you.", 1],
    ["I’m going to make sure you feel every ounce of pain you’ve caused.", 1],
    ["I hope you like your regrets, because that’s all you’ll have left.", 1],
    ["You’ll be sorry for crossing me. Count on it.", 1],
    ["One of these days, you’ll regret everything you’ve done.", 1],
    ["You don’t want to push me any further. You’ve been warned.", 1],
    ["I’ve had enough of your nonsense. It’s time to settle this.", 1],
    ["You’re on borrowed time. Don’t think I’ll forget.", 1],
    ["I’m coming for you. There’s no escape.", 1],
    ["If I were you, I’d start running while you still can.", 1],
    ["You won’t be able to hide from me. I’ll find you.", 1],
    ["You’ve crossed the line, and now there’s no turning back.", 1],
    ["You won’t know what hit you when I get my hands on you.", 1],
    ["You’ve made the biggest mistake of your life. Now, face the consequences.", 1],
    ["You’ll regret the day you ever met me.", 1],
    ["I’m not someone you want to mess with. Stay away.", 1],
    ["It’s too late to apologize now. You’ve sealed your fate.", 1],
    ["If you know what’s good for you, you’ll stay out of my way.", 1],
    ["You should have stayed quiet. Now it’s too late.", 1],
    ["You’ll pay for every second I’ve had to waste on you.", 1],
    ["I’ll make sure you regret ever crossing my path.", 1],
    ["You’ve made your bed. Now lie in it.", 1],
    ["Keep provoking me, and you’ll see just how far I can go.", 1],
    ["This isn’t over. Not by a long shot.", 1],
    ["I’ll make sure you never forget what happens next.", 1],
    ["You’ve made a fatal mistake, and now it’s too late to fix it.", 1],
    ["Don’t test me. You won’t like the results.", 1],
    ["I’ll make sure you feel every ounce of pain you’ve caused.", 1],
    ["You’ve made me your enemy, and now you’ll suffer the consequences.", 1],
    ["Don’t think you’ll get away with this. I’ll make sure of it.", 1],
    ["You should have stayed out of my business. Now, it’s too late.", 1],
    ["I won’t forget what you did. You’ll regret it soon enough.", 1],
    ["You’re about to regret ever crossing me.", 1],
    ["I won’t stop until you regret everything you’ve done to me.", 1],
    ["You better watch your back, because I’m coming for you.", 1],
    ["I’ll make you wish you never crossed me.", 1],
    ["Don’t worry. I’ll make sure you pay for this.", 1],
    ["Your time is running out. It’s only a matter of time.", 1],
    ["I’ve got a long memory, and I’m coming for you.", 1],
    ["You think you’re safe, but I’ll make sure you’re not.", 1],
    ["Your actions have consequences, and I’ll make sure you face them.", 1],
    ["There’s no escaping what’s coming for you.", 1],
    ["You’re going to wish you never crossed my path.", 1],
    ["It’s only a matter of time before you pay for what you did.", 1],
    ["You’re about to find out what happens when you cross me.", 1],
    ["There’s no way out now. You’ve pushed me too far.", 1],
    ["You’ve messed with the wrong person. Prepare yourself.", 1],
    ["I hope you’re ready for the consequences of your actions.", 1],
    ["I’m not done with you yet. You’ll regret this soon enough.", 1],
    ["I’ll make sure you know exactly what regret feels like.", 1],
    ["You’ve made a mistake you’ll never be able to undo.", 1],
    ["I’ll make you regret ever thinking you could get away with this.", 1],
    ["You should have known better than to mess with me.", 1],
    ["I’ll make sure your regret lasts a lifetime.", 1],
    ["You’re going to wish you never did what you did to me.", 1],
    ["It’s too late to apologize now. Your fate is sealed.", 1],
    ["I’ll make sure the price you pay is steep.", 1],
    ["There’s no turning back now. You’ve made your bed.", 1],
    ["You’ve made a serious mistake, and now you’ll pay for it.", 1],
    ["I’m coming for you, and there’s nowhere you can hide.", 1],
    ["You won’t get away with this. I’ll make sure of it.", 1],
    ["I’m going to make sure you regret everything you’ve done.", 1],
    ["You can’t escape what’s coming for you.", 1],
    ["You’ll regret ever crossing my path. Count on it.", 1],
    ["I’m going to make sure you regret this for the rest of your life.", 1],
    ["You’ve got nowhere to run. I’ll make sure of that.", 1],
    ["You think you’ve won? Wait until you see what’s coming.", 1],
    ["I’ve got a plan, and you’re not going to like it.", 1],
    ["You won’t know what hit you when I’m done with you.", 1],
    ["I’ll make sure you regret every word you’ve said.", 1],
    ["There’s no escape from this. You’ll pay for what you did.", 1],
    ["Don’t think you’re safe just because I haven’t acted yet.", 1],
    ["I’m going to make you wish you were never born.", 1],
    ["You’ve pushed me too far, and now you’re going to pay.", 1],
    ["You’re going to regret everything you’ve ever done to me.", 1],
    ["Keep pushing, and you’ll see just how far I’ll go.", 1],
    ["You’ll never see it coming, but I’ll make you regret it.", 1],
    ["You’ve made a fatal error, and now it’s time to pay.", 1],
    ["You’ve crossed a line you’ll never be able to uncross.", 1],
    ["You think you can get away with this? Think again.", 1],
    ["I’ll make sure you never forget what happens next.", 1],
    ["You’ve sealed your fate. There’s no going back now.", 1],
    ["You’re going to wish you never met me.", 1],
    ["I’m not done with you. Not by a long shot.", 1],
    ["Your time is running out. You’ll pay for this soon enough.", 1]
]


